AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    FastAPI aws lambda example
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hierarchy_services
      CodeUri: ./hierarchy_services
      Handler: hierarchy_services.main.handler
      Runtime: python3.9
      Layers:
        - !Ref SharedLayer
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        NonRoot:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLayer
      Description: Dependencies for sam app
      ContentUri: shared/
      CompatibleRuntimes:
        - python3.9
      # LicenseInfo: 'MIT'
      RetentionPolicy: Retain