AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    FastAPI aws lambda example
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app
      Handler: main.handler
      Runtime: python3.9
      Layers:
        - !Ref TempConversionDepLayer
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        NonRoot:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  TempConversionDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-app-dependencies
      Description: Dependencies for sam app [temp-units-conv]
      ContentUri: shared/
      CompatibleRuntimes:
        - python3.9
      # LicenseInfo: 'MIT'
      RetentionPolicy: Retain